baseURL = "https://snobiznmore.com/"
languageCode = "en-us"
title = "Snobiz n' More"
theme = "snobiz"

summaryLength = 10 # Configure how long the post summary should be on the homepage.

[pagination]
pagerSize = 4

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true
